---
- name: Install QEMU and OVMF
  ansible.builtin.package:
    name:
      - qemu-desktop
      - edk2-ovmf
    state: present

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify]
  when: verify_enabled
