# - hosts: localhost
#   become: true
#   roles:
#     - ansible-ctrl.init

- hosts: virtual_hosts
  become: true
  roles:
    - arch-iso-install
    # - network.init
    # - wm.init
    # - git.init

# - hosts: windows_hosts
#   roles: