# - hosts: localhost
#   become: true
#   roles:
#     - ansible-ctrl.init

- hosts: virtual_hosts
  become: true
  roles:
    - role: arch-iso-install
      when: ansible_nodename == 'archiso'
      ansible_user: root
    - role: network

# - hosts: windows_hosts
#   roles: