---
- name: Install Arch Linux
  hosts: all
  become: true
  vars:
    install_root: /mnt

  roles:
    # Storage Stack
    - role: partition
    - role: encryption
    - role: filesystem

    # OS Installation
    - role: pacstrap

    # Configuration
    - role: time
    - role: locale
    - role: hosts
    - role: network
    - role: sshd
    - role: user
    - role: ssh_client

    # Boot
    - role: initramfs
    - role: bootloader

  tasks:
    - name: Ensure target ansible directory exists
      file:
        path: "{{ install_root }}/root/ansible"
        state: directory
        mode: '0755'

    - name: Prepare Ansible for post-install
      copy:
        src: "{{ playbook_dir }}/"
        dest: "{{ install_root }}/root/ansible/"
        remote_src: true
