---
- name: Create User
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups:
      - wheel
    shell: "{{ user_shell }}"
    append: true
    state: present

- name: Set Password
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
  when: user_password | length > 0
  no_log: true

- name: Sudoers
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/wheel"
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: SSH Directory
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ user_name }}"

- name: Authorized Keys
  ansible.builtin.copy:
    content: "{{ user_ssh_key }}"
    dest: "/home/{{ user_name }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ user_name }}"
  when: user_ssh_key | length > 0
  failed_when: false

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify]
  when: verify_enabled
