virtual_hosts:
  hosts:
    # arch-test-1.gnome.network:
    #   ansible_host: 192.168.119.23
    arch-test-2.gnome.network:
      ansible_host: 172.30.95.1
windows_hosts:
  hosts:
    whimsyforge.gnome.network:
      ansible_host: 192.168.112.1