virtual_hosts:
  hosts:
    arch-test.gnome.network:
      ansible_host: 192.168.122.27
      arch_iso_install_install_drive: /dev/vdb
windows_hosts:
  hosts:
    # whimsyforge.gnome.network:
    #   ansible_host: 192.168.112.1