# Default variables used throughout the role

install_drive: /dev/sda

encryption:
  enabled: true
  password: "{{ lookup('env', 'ENCRYPTION_PASSWORD') }}"

btrfs:
  enabled: true
  subvols: 
    - sub: '@snapshots'
      path: '.snapshots'
    - sub: '@home'
      path: 'home'
    - sub: '@log'
      path: 'var/log'
    - sub: '@cache'
      path: 'var/cache'
    - sub: '@tmp'
      path: 'var/tmp'
    - sub: '@data'
      path: 'data'
      disable_cow: true

timezone: America/Chicago

user:
  name: on3ir
  password: "{{ lookup('env', 'USER_PASSWORD') }}"
  full: 'on3iropolos'
  email: on3iropolos@gmail.com
  pub_key_location: "/root/.ssh/on3iropolos-ssh.pub"

bootloader: grub
boot_esp: /boot/efi