---
- name: Verify ansible.cfg
  ansible.builtin.stat:
    path: /etc/ansible/ansible.cfg
  register: ansible_cfg

- name: Assert ansible.cfg exists
  ansible.builtin.assert:
    that:
      - ansible_cfg.stat.exists
    fail_msg: "Ansible configuration file was not found at /etc/ansible/ansible.cfg"
