- name: Create root
  ansible.builtin.command: btrfs subvolume create /mnt/@
  changed_when: true

- name: Create other subvols
  ansible.builtin.command: btrfs subvolume create /mnt/{{ item.sub }}
  changed_when: true
  loop: "{{ arch_iso_install_btrfs.subvols }}"

- name: Unmount /mnt
  ansible.posix.mount:
    path: /mnt
    state: unmounted

- name: Mount btrfs root subvolume
  ansible.posix.mount:
    path: /mnt
    src: '{{ "/dev/mapper/cryptroot" if use_encryption else root_part }}'
    fstype: btrfs
    opts: "compress=zstd,discard=async,subvol=@"
    state: mounted

- name: Create mountpoint for btrfs subvolumes
  ansible.builtin.file:
    path: /mnt/{{ item.path }}
    state: directory
  loop: "{{ arch_iso_install_btrfs.subvols }}"

- name: Mount btrfs subvolumes
  ansible.posix.mount:
    path: /mnt/{{ item.path }}
    src: '{{ "/dev/mapper/cryptroot" if use_encryption else root_part }}'
    fstype: btrfs
    opts: "compress=zstd,discard=async,subvol={{ item.sub }}"
    state: mounted
  loop: "{{ arch_iso_install_btrfs.subvols }}"

- name: Disable CoW for subvols with disable_cow = true
  ansible.builtin.file:
    path: /mnt/{{ item.path }}
    attributes: C
  loop: "{{ arch_iso_install_btrfs.subvols }}"
  when: item.disable_cow | default(false)
