- name: Check if device is already LUKS encrypted
  ansible.builtin.command: cryptsetup isLuks {{ root_part }}
  register: luks_check
  failed_when: false
  changed_when: false

- name: Encrypt drive
  # ref: LUKS1 required for grub: https://wiki.archlinux.org/title/GRUB#Encrypted_/boot
  ansible.builtin.shell: |
    echo -n "{{ arch_iso_install_encryption.password }}" | cryptsetup luksFormat --type {{ 'luks1' if arch_iso_install_bootloader == 'grub' else 'luks2' }} -q {{ root_part }} -
  when: luks_check.rc != 0
  no_log: true

- name: Open encrypted drive
  ansible.builtin.shell: |
    echo -n "{{ arch_iso_install_encryption.password }}" | cryptsetup open {{ root_part }} cryptroot -
  no_log: true
