# https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#Encrypted_boot_partition_(GRUB)
- name: Setup grub for encryption
  ansible.builtin.lineinfile:
    dest: /mnt/etc/default/grub
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - { regex: "^#?GRUB_ENABLE_CRYPTODISK", line: "GRUB_ENABLE_CRYPTODISK=y"}
    - { regex: "^#?GRUB_CMDLINE_LINUX", line: 'GRUB_CMDLINE_LINUX="cryptdevice={{ root_part }}:cryptroot:allow-discards cryptkey=/crypto_keyfile.bin"'}
    - { regex: "^#?GRUB_CMDLINE_LINUX_DEFAULT", line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"'}
    - { regex: "^#?GRUB_DISABLE_OS_PROBER", line: "GRUB_DISABLE_OS_PROBER=false"}
  when: use_encryption

# https://wiki.archlinux.org/title/GRUB#UEFI_systems
- name: Install grub (UEFI mode)
  ansible.builtin.command: arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory={{ arch_iso_install_boot_esp }} --bootloader-id=GRUB-ARCH
  changed_when: true
  when: arch_iso_install_boot_mode == 'uefi'

# https://wiki.archlinux.org/title/GRUB#BIOS_systems
- name: Install grub (BIOS mode)
  ansible.builtin.command: arch-chroot /mnt grub-install --target=i386-pc {{ arch_iso_install_install_drive }}
  changed_when: true
  when: arch_iso_install_boot_mode == 'bios'

- name: Create grub config
  ansible.builtin.command: arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: true
