- name: Create user account
  ansible.builtin.command: arch-chroot /mnt useradd -s /bin/bash -m --user-group -G wheel {{ arch_iso_install_user.name }}
  changed_when: true

- name: Create user password
  ansible.builtin.command: arch-chroot /mnt sh -c 'echo {{ arch_iso_install_user.name }}:{{ arch_iso_install_user.password }} | chpasswd'
  changed_when: true

- name: Create user's ssh directory
  ansible.builtin.file:
    path: /mnt/home/{{ arch_iso_install_user.name }}/.ssh
    state: directory
    mode: "0700"

- name: Copy over ssh key from current Ansible controller as an authorized key
  ansible.builtin.copy:
    src: "{{ arch_iso_install_user.pub_key_location }}"
    dest: /mnt/home/{{ arch_iso_install_user.name }}/.ssh/authorized_keys
    mode: "0600"

- name: Set mode, owner, and group on user's authorized_key file
  ansible.builtin.command: >-
    arch-chroot /mnt chown -R {{ arch_iso_install_user.name }}:{{ arch_iso_install_user.name }}
    /home/{{ arch_iso_install_user.name }}/.ssh/
  changed_when: true

- name: Give passwordless sudo access to wheel group
  ansible.builtin.copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /mnt/etc/sudoers.d/wheel
    validate: /usr/sbin/visudo --check --file=%s
