---
- name: List all networks
  ansible.builtin.command:
    cmd: virsh -c qemu:///system net-list --name --all
  register: all_nets
  changed_when: false

- name: Define default network if not present
  ansible.builtin.command:
    cmd: virsh -c qemu:///system net-define /etc/libvirt/qemu/networks/{{ vm_host_network_name }}.xml
  when: vm_host_network_name not in all_nets.stdout_lines
  changed_when: true

- name: List active networks
  ansible.builtin.command:
    cmd: virsh -c qemu:///system net-list --name
  register: active_nets
  changed_when: false

- name: Ensure default network is autostart
  ansible.builtin.command:
    cmd: virsh -c qemu:///system net-autostart {{ vm_host_network_name }}
  changed_when: false

- name: Start default network if not active
  ansible.builtin.command:
    cmd: virsh -c qemu:///system net-start {{ vm_host_network_name }}
  when: vm_host_network_name not in active_nets.stdout_lines
  changed_when: true
