---
- name: Install libvirt packages
  ansible.builtin.package:
    name: "{{ vm_host_libvirt_packages }}"
    state: present

- name: Start and enable libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: true
  when: ansible_user_id != 'root'
