---
- name: Install AUR dependencies
  ansible.builtin.package:
    name:
      - base-devel
      - git
      - paru
    state: present

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify]
  when: verify_enabled
