---
- name: Install AUR dependencies
  ansible.builtin.package:
    name:
      - base-devel
      - git
      - paru
    state: present

- name: Create aur_builder user
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
    system: true
    shell: /bin/bash

- name: Allow aur_builder to run pacman without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: '0644'
    validate: 'visudo -cf %s'

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify]
  when: verify_enabled
