---
- name: Verify paru binary exists
  ansible.builtin.stat:
    path: "{{ install_root if install_root | length > 0 else '' }}/usr/bin/paru"
  register: paru_stat

- name: Assert paru binary exists
  ansible.builtin.assert:
    that:
      - paru_stat.stat.exists
    fail_msg: "The paru binary was not found at {{ install_root if install_root | length > 0 else '' }}/usr/bin/paru"
