---
- name: Verify yay binary exists
  ansible.builtin.stat:
    path: "{{ install_root if install_root | length > 0 else '' }}/usr/bin/yay"
  register: yay_stat

- name: Assert yay binary exists
  ansible.builtin.assert:
    that:
      - yay_stat.stat.exists
    fail_msg: "The yay binary was not found at {{ install_root if install_root | length > 0 else '' }}/usr/bin/yay"
