---
- name: Enable NetworkManager (Chroot)
  ansible.builtin.command: arch-chroot {{ install_root }} systemctl enable NetworkManager
  changed_when: true
  when: install_root | length > 0

- name: Enable NetworkManager (Native)
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
  when: install_root | length == 0
