---
- name: Install Spotify from AUR
  kewlfft.aur.aur:
    name: spotify
    state: present
  become: true
  become_user: aur_builder
  tags: [spotify]

- name: Spotify config directory
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.config/spotify"
    state: directory
    mode: '0755'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: user_name != "root"
  tags: [spotify]

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify, spotify]
  when: verify_enabled
