---
- name: Install GNOME desktop environment
  ansible.builtin.package:
    name:
      - gnome
      - gnome-extra
    state: present

- name: Enable GDM service
  ansible.builtin.systemd:
    name: gdm
    enabled: true
    state: started

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify]
  when: verify_enabled
