---
pacstrap_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - vim
  - nano
  - git
  - less
  - man-db
  - man-pages
  - python
  - ansible
  - sudo
  - btrfs-progs
  - networkmanager
  - grub
  - efibootmgr
  - openssh
  - python-passlib
verify_enabled: true
