---
install_root: ""

# SSH Identities for Git and other services
user_ssh_identities: []
# Example:
# user_ssh_identities:
#   - name: github
#     filename: github-ssh-key
#     private_key: "{{ lookup('env', 'GITHUB_SSH_PRIVATE_KEY') }}"
#     public_key: "{{ lookup('env', 'GITHUB_SSH_PUBLIC_KEY') }}"
#     host: github.com
