# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# Install systemd and other required packages
RUN apt-get update && apt-get install -y \
    systemd \
    systemd-sysv \
    python3 \
    python3-pip \
    sudo \
    iproute2 \
    iptables \
    which \
    && rm -rf /var/lib/apt/lists/*

# Remove unnecessary systemd services
RUN find /etc/systemd/system /lib/systemd/system -path '*.wants/*' -not -name '*journald*' -not -name '*systemd-tmpfiles*' -not -name '*systemd-user-sessions*' -delete

# Create systemd machine-id
RUN systemd-machine-id-setup

# Set up systemd as the init system
VOLUME [ "/sys/fs/cgroup" ]

CMD ["/sbin/init"]
