---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update pacman package cache
      ansible.builtin.raw: pacman -Sy --noconfirm
      changed_when: false

    - name: Install python for Ansible
      ansible.builtin.raw: pacman -S --noconfirm python
      changed_when: false

    - name: Install openssh for sshd service
      ansible.builtin.raw: pacman -S --noconfirm openssh
      changed_when: false

    - name: Gather facts after Python installation
      ansible.builtin.setup:
