---
- name: Verify fstab existence
  ansible.builtin.stat:
    path: /mnt/etc/fstab
  register: fstab_file

- name: Assert fstab exists
  ansible.builtin.assert:
    that:
      - fstab_file.stat.exists
    fail_msg: "The fstab file was not created at /mnt/etc/fstab"

- name: Verify base packages installed
  ansible.builtin.command: arch-chroot /mnt pacman -Qi {{ item }}
  loop: "{{ pacstrap_packages | default([]) }}"
  register: pacstrap_pkg_check
  changed_when: false
  failed_when: pacstrap_pkg_check.rc != 0
