# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# Install systemd and other required packages
RUN pacman -Sy --noconfirm \
    systemd \
    systemd-sysvcompat \
    python \
    python-pip \
    sudo \
    iproute2 \
    iptables \
    which \
    base-devel \
    git \
    && pacman -Scc --noconfirm

# Remove unnecessary systemd services
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

# Create systemd machine-id
RUN systemd-machine-id-setup

# Set up systemd as the init system
VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/lib/systemd/systemd"]
