- name: setup ramdisk for btrfs
  lineinfile:
    dest: /mnt/etc/mkinitcpio.conf
    regexp: ^BINARIES
    line: 'BINARIES=(btrfs)'
  when: use_btrfs
  notify: create_ramdisk

- name: run encryption items for ramdisk if needed
  block:
    - name: create random file for boot decryption
      community.general.filesize:
        path: /mnt/crypto_keyfile.bin
        size: 2 MiB
        source: /dev/urandom
    - name: encrypt drive
      community.crypto.luks_device:
        device: "{{ root_part }}"
        passphrase: "{{ encryption.password }}"
        new_keyfile: /mnt/crypto_keyfile.bin
    - name: setup ramdisk for disk encryption | grub
      lineinfile:
        dest: /mnt/etc/mkinitcpio.conf
        regexp: ^HOOKS=
        line: 'HOOKS=(base udev autodetect modconf block encrypt filesystems keyboard fsck)'
      when: bootloader == 'grub'
    - name: setup ramdisk for encryption file
      lineinfile:
        dest: /mnt/etc/mkinitcpio.conf
        regexp: ^FILES=
        line: 'FILES=(/crypto_keyfile.bin)'
  notify: create_ramdisk
  when: use_encryption

- name: Flush handlers
  meta: flush_handlers