- name: Create /etc/ansible directory
  file:
    path: /etc/ansible
    state: directory
    mode: 0755

- name: Ensure ansible is configured
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    mode: 0600