---
- name: Set Hostname
  ansible.builtin.copy:
    dest: "/etc/hostname"
    content: "{{ hostname }}"
    mode: '0644'

- name: Set Hosts
  ansible.builtin.shell: |
    true
  changed_when: false

- name: Verification
  ansible.builtin.include_tasks: verify.yml
  tags: [verify]
  when: verify_enabled
