name: Ansible Lint

on:
  pull_request:
    branches: [ main ] # Assuming 'main' is the default branch

jobs:
  lint:
    name: Lint Ansible Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install Ansible and ansible-lint
        run: pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint .
